server:
  port : 5050
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crees
    username: crees
    password: crees
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
resilience4j:
  instances:
    ridesService:
      timeoutDuration=5s: