server:
  port: ${SERVICE_PORT}
spring:
  mvc:
    async:
      request-timeout: ${TIMEOUT_MS}
  datasource:
    url: ${DB_RIDES_URL}
    username: ${DB_RIDES_USER}
    password: ${DB_RIDES_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true

  jpa:
    properties:
      javax:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false

service-discovery:
  host: ${SERVICE_DISCOVERY_HOST}
  port: ${SERVICE_DISCOVERY_PORT}