server:
  port : 5050

spring:
  mvc:
    async:
      request-timeout: 2000
  datasource:
    url: jdbc:postgresql://localhost:5433/ridesDB
    username: user2
    password: password2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true

  jpa:
    properties:
      javax:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false