version: '3.8'

services:
  gateway:
    image: gateway
    container_name: gateway
    restart: always
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
    depends_on:
      - redis-cache

  service-discovery:
    image: service-discovery
    container_name: service-discovery
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
    depends_on:
      - redis-cache

  rides:
    image: rides-service:latest

    deploy:
      mode: replicated
      replicas: 3
    links:
      - postgres2
    ports:
      - "8080-8082:8080"
    environment:
      - TIMEOUT_MS=5000
      - DB_RIDES_URL=jdbc:postgresql://postgres2/ridesDB
      - DB_RIDES_USER=user2
      - DB_RIDES_PASSWORD=password2
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - SERVICE_DISCOVERY_HOST=service-discovery
      - SERVICE_DISCOVERY_PORT=3000
      - SERVICE_PORT=8080

    depends_on:
      - service-discovery
      - postgres2
      - rabbitmq

  drivers:
    image: drivers-service:latest

    deploy:
      mode: replicated
      replicas: 2
    links:
      - postgres1
    ports:
      - "7070-7072:7070"
    environment:
      - TIMEOUT_MS=5000
      - DB_RIDES_URL=jdbc:postgresql://postgres1/driversDB
      - DB_RIDES_USER=user1
      - DB_RIDES_PASSWORD=password1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - SERVICE_DISCOVERY_HOST=service-discovery
      - SERVICE_DISCOVERY_PORT=3000
      - SERVICE_PORT=7070

    depends_on:
      - service-discovery
      - postgres1
      - rabbitmq

  postgres1:
    image: postgres:latest
    container_name: driversDB
    environment:
      POSTGRES_DB: driversDB
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"
    volumes:
      - postgres1-data:/var/lib/postgresql/data

  postgres2:
    image: postgres:latest
    container_name: ridesDB
    environment:
      POSTGRES_DB: ridesDB
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
    ports:
      - "5433:5432"
    volumes:
      - postgres2-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMQ
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  redis-cache:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

volumes:
  postgres1-data:
  postgres2-data:
  cache: