version: '3.1'

services:

  postgres1:
    image: postgres:latest
    container_name: driversDB
    environment:
      POSTGRES_DB: driversDB
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"
    volumes:
      - postgres1-data:/var/lib/postgresql/data

  postgres2:
    image: postgres:latest
    container_name: ridesDB
    environment:
      POSTGRES_DB: ridesDB
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
    ports:
      - "5433:5432"
    volumes:
      - postgres2-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMQ
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres1-data:
  postgres2-data: