server:
  port : 6060

spring:
  mvc:
    async:
      request-timeout: 2000
  datasource:
    url: jdbc:postgresql://localhost:5432/driversDB
    username: user1
    password: password1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 20
#          max-interval: 3s
          multiplier: 1.1

  jpa:
    properties:
      javax:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
