server:
  port : ${SERVICE_PORT}

spring:
  sql.init.mode: always
  mvc:
    async:
      request-timeout: ${TIMEOUT_MS}
  datasource:
    url: ${DB_DRIVERS_URL}
    username: ${DB_DRIVERS_USER}
    password: ${DB_DRIVERS_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 5
#          max-interval: 3s
          multiplier: 1.1

  jpa:
    defer-datasource-initialization: true
    properties:
      javax:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false

service-discovery:
  host: ${SERVICE_DISCOVERY_HOST}
  port: ${SERVICE_DISCOVERY_PORT}