global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rides'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:3030', 'host.docker.internal:3031', 'host.docker.internal:3032']
        labels:
          application: 'Rides Service'